//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportToVufind.test {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReaderInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ReaderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FamilyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FatherNameField;
        
        private System.DateTime DateBirthField;
        
        private bool IsRemoteReaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BarCodeField;
        
        private System.DateTime DateRegistrationField;
        
        private System.DateTime DateReRegistrationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileTelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private int WorkDepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashedPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SaltField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberReaderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FamilyName {
            get {
                return this.FamilyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyNameField, value) != true)) {
                    this.FamilyNameField = value;
                    this.RaisePropertyChanged("FamilyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FatherName {
            get {
                return this.FatherNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FatherNameField, value) != true)) {
                    this.FatherNameField = value;
                    this.RaisePropertyChanged("FatherName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime DateBirth {
            get {
                return this.DateBirthField;
            }
            set {
                if ((this.DateBirthField.Equals(value) != true)) {
                    this.DateBirthField = value;
                    this.RaisePropertyChanged("DateBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool IsRemoteReader {
            get {
                return this.IsRemoteReaderField;
            }
            set {
                if ((this.IsRemoteReaderField.Equals(value) != true)) {
                    this.IsRemoteReaderField = value;
                    this.RaisePropertyChanged("IsRemoteReader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BarCode {
            get {
                return this.BarCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BarCodeField, value) != true)) {
                    this.BarCodeField = value;
                    this.RaisePropertyChanged("BarCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DateRegistration {
            get {
                return this.DateRegistrationField;
            }
            set {
                if ((this.DateRegistrationField.Equals(value) != true)) {
                    this.DateRegistrationField = value;
                    this.RaisePropertyChanged("DateRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime DateReRegistration {
            get {
                return this.DateReRegistrationField;
            }
            set {
                if ((this.DateReRegistrationField.Equals(value) != true)) {
                    this.DateReRegistrationField = value;
                    this.RaisePropertyChanged("DateReRegistration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string MobileTelephone {
            get {
                return this.MobileTelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileTelephoneField, value) != true)) {
                    this.MobileTelephoneField = value;
                    this.RaisePropertyChanged("MobileTelephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int WorkDepartment {
            get {
                return this.WorkDepartmentField;
            }
            set {
                if ((this.WorkDepartmentField.Equals(value) != true)) {
                    this.WorkDepartmentField = value;
                    this.RaisePropertyChanged("WorkDepartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string HashedPassword {
            get {
                return this.HashedPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.HashedPasswordField, value) != true)) {
                    this.HashedPasswordField = value;
                    this.RaisePropertyChanged("HashedPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Salt {
            get {
                return this.SaltField;
            }
            set {
                if ((object.ReferenceEquals(this.SaltField, value) != true)) {
                    this.SaltField = value;
                    this.RaisePropertyChanged("Salt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NumberReader {
            get {
                return this.NumberReaderField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberReaderField, value) != true)) {
                    this.NumberReaderField = value;
                    this.RaisePropertyChanged("NumberReader");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="test.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем NumberReader из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReaderInfo", ReplyAction="*")]
        ExportToVufind.test.GetReaderInfoResponse GetReaderInfo(ExportToVufind.test.GetReaderInfoRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authorize", ReplyAction="*")]
        ExportToVufind.test.AuthorizeResponse Authorize(ExportToVufind.test.AuthorizeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем strPassword из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HashPass", ReplyAction="*")]
        ExportToVufind.test.HashPassResponse HashPass(ExportToVufind.test.HashPassRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLoginType", ReplyAction="*")]
        ExportToVufind.test.GetLoginTypeResponse GetLoginType(ExportToVufind.test.GetLoginTypeRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем login из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUser", ReplyAction="*")]
        ExportToVufind.test.GetUserResponse GetUser(ExportToVufind.test.GetUserRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем IDSession из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertIntoBasket", ReplyAction="*")]
        ExportToVufind.test.InsertIntoBasketResponse InsertIntoBasket(ExportToVufind.test.InsertIntoBasketRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем PINs из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertArrayIntoBasket", ReplyAction="*")]
        ExportToVufind.test.InsertArrayIntoBasketResponse InsertArrayIntoBasket(ExportToVufind.test.InsertArrayIntoBasketRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем IDDATA из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExemplarStatus", ReplyAction="*")]
        ExportToVufind.test.GetExemplarStatusResponse GetExemplarStatus(ExportToVufind.test.GetExemplarStatusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookStatus", ReplyAction="*")]
        ExportToVufind.test.GetBookStatusResponse GetBookStatus(ExportToVufind.test.GetBookStatusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем id из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookInfoByID", ReplyAction="*")]
        ExportToVufind.test.GetBookInfoByIDResponse GetBookInfoByID(ExportToVufind.test.GetBookInfoByIDRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем invNumber из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookInfoByInvNumber", ReplyAction="*")]
        ExportToVufind.test.GetBookInfoByInvNumberResponse GetBookInfoByInvNumber(ExportToVufind.test.GetBookInfoByInvNumberRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем pwd из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePWD", ReplyAction="*")]
        ExportToVufind.test.ChangePWDResponse ChangePWD(ExportToVufind.test.ChangePWDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReaderInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReaderInfo", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetReaderInfoRequestBody Body;
        
        public GetReaderInfoRequest() {
        }
        
        public GetReaderInfoRequest(ExportToVufind.test.GetReaderInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReaderInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberReader;
        
        public GetReaderInfoRequestBody() {
        }
        
        public GetReaderInfoRequestBody(string NumberReader) {
            this.NumberReader = NumberReader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReaderInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReaderInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetReaderInfoResponseBody Body;
        
        public GetReaderInfoResponse() {
        }
        
        public GetReaderInfoResponse(ExportToVufind.test.GetReaderInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReaderInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExportToVufind.test.ReaderInfo GetReaderInfoResult;
        
        public GetReaderInfoResponseBody() {
        }
        
        public GetReaderInfoResponseBody(ExportToVufind.test.ReaderInfo GetReaderInfoResult) {
            this.GetReaderInfoResult = GetReaderInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authorize", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.AuthorizeRequestBody Body;
        
        public AuthorizeRequest() {
        }
        
        public AuthorizeRequest(ExportToVufind.test.AuthorizeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthorizeRequestBody() {
        }
        
        public AuthorizeRequestBody(string login, string password) {
            this.login = login;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.AuthorizeResponseBody Body;
        
        public AuthorizeResponse() {
        }
        
        public AuthorizeResponse(ExportToVufind.test.AuthorizeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthorizeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthorizeResult;
        
        public AuthorizeResponseBody() {
        }
        
        public AuthorizeResponseBody(string AuthorizeResult) {
            this.AuthorizeResult = AuthorizeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashPassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashPass", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.HashPassRequestBody Body;
        
        public HashPassRequest() {
        }
        
        public HashPassRequest(ExportToVufind.test.HashPassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HashPassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strSol;
        
        public HashPassRequestBody() {
        }
        
        public HashPassRequestBody(string strPassword, string strSol) {
            this.strPassword = strPassword;
            this.strSol = strSol;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HashPassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HashPassResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.HashPassResponseBody Body;
        
        public HashPassResponse() {
        }
        
        public HashPassResponse(ExportToVufind.test.HashPassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HashPassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HashPassResult;
        
        public HashPassResponseBody() {
        }
        
        public HashPassResponseBody(string HashPassResult) {
            this.HashPassResult = HashPassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginType", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetLoginTypeRequestBody Body;
        
        public GetLoginTypeRequest() {
        }
        
        public GetLoginTypeRequest(ExportToVufind.test.GetLoginTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public GetLoginTypeRequestBody() {
        }
        
        public GetLoginTypeRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLoginTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLoginTypeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetLoginTypeResponseBody Body;
        
        public GetLoginTypeResponse() {
        }
        
        public GetLoginTypeResponse(ExportToVufind.test.GetLoginTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLoginTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLoginTypeResult;
        
        public GetLoginTypeResponseBody() {
        }
        
        public GetLoginTypeResponseBody(string GetLoginTypeResult) {
            this.GetLoginTypeResult = GetLoginTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUser", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetUserRequestBody Body;
        
        public GetUserRequest() {
        }
        
        public GetUserRequest(ExportToVufind.test.GetUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        public GetUserRequestBody() {
        }
        
        public GetUserRequestBody(string login) {
            this.login = login;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetUserResponseBody Body;
        
        public GetUserResponse() {
        }
        
        public GetUserResponse(ExportToVufind.test.GetUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExportToVufind.test.ReaderInfo GetUserResult;
        
        public GetUserResponseBody() {
        }
        
        public GetUserResponseBody(ExportToVufind.test.ReaderInfo GetUserResult) {
            this.GetUserResult = GetUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoBasketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoBasket", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.InsertIntoBasketRequestBody Body;
        
        public InsertIntoBasketRequest() {
        }
        
        public InsertIntoBasketRequest(ExportToVufind.test.InsertIntoBasketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoBasketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PIN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDSession;
        
        public InsertIntoBasketRequestBody() {
        }
        
        public InsertIntoBasketRequestBody(int PIN, string IDSession) {
            this.PIN = PIN;
            this.IDSession = IDSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertIntoBasketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertIntoBasketResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.InsertIntoBasketResponseBody Body;
        
        public InsertIntoBasketResponse() {
        }
        
        public InsertIntoBasketResponse(ExportToVufind.test.InsertIntoBasketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertIntoBasketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertIntoBasketResult;
        
        public InsertIntoBasketResponseBody() {
        }
        
        public InsertIntoBasketResponseBody(bool InsertIntoBasketResult) {
            this.InsertIntoBasketResult = InsertIntoBasketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertArrayIntoBasketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertArrayIntoBasket", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.InsertArrayIntoBasketRequestBody Body;
        
        public InsertArrayIntoBasketRequest() {
        }
        
        public InsertArrayIntoBasketRequest(ExportToVufind.test.InsertArrayIntoBasketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertArrayIntoBasketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ExportToVufind.test.ArrayOfInt PINs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string IDSession;
        
        public InsertArrayIntoBasketRequestBody() {
        }
        
        public InsertArrayIntoBasketRequestBody(ExportToVufind.test.ArrayOfInt PINs, string IDSession) {
            this.PINs = PINs;
            this.IDSession = IDSession;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertArrayIntoBasketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertArrayIntoBasketResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.InsertArrayIntoBasketResponseBody Body;
        
        public InsertArrayIntoBasketResponse() {
        }
        
        public InsertArrayIntoBasketResponse(ExportToVufind.test.InsertArrayIntoBasketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertArrayIntoBasketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool InsertArrayIntoBasketResult;
        
        public InsertArrayIntoBasketResponseBody() {
        }
        
        public InsertArrayIntoBasketResponseBody(bool InsertArrayIntoBasketResult) {
            this.InsertArrayIntoBasketResult = InsertArrayIntoBasketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExemplarStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExemplarStatus", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetExemplarStatusRequestBody Body;
        
        public GetExemplarStatusRequest() {
        }
        
        public GetExemplarStatusRequest(ExportToVufind.test.GetExemplarStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExemplarStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IDDATA;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BaseName;
        
        public GetExemplarStatusRequestBody() {
        }
        
        public GetExemplarStatusRequestBody(string IDDATA, string BaseName) {
            this.IDDATA = IDDATA;
            this.BaseName = BaseName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExemplarStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExemplarStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetExemplarStatusResponseBody Body;
        
        public GetExemplarStatusResponse() {
        }
        
        public GetExemplarStatusResponse(ExportToVufind.test.GetExemplarStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExemplarStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExemplarStatusResult;
        
        public GetExemplarStatusResponseBody() {
        }
        
        public GetExemplarStatusResponseBody(string GetExemplarStatusResult) {
            this.GetExemplarStatusResult = GetExemplarStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookStatus", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetBookStatusRequestBody Body;
        
        public GetBookStatusRequest() {
        }
        
        public GetBookStatusRequest(ExportToVufind.test.GetBookStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetBookStatusRequestBody() {
        }
        
        public GetBookStatusRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetBookStatusResponseBody Body;
        
        public GetBookStatusResponse() {
        }
        
        public GetBookStatusResponse(ExportToVufind.test.GetBookStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookStatusResult;
        
        public GetBookStatusResponseBody() {
        }
        
        public GetBookStatusResponseBody(string GetBookStatusResult) {
            this.GetBookStatusResult = GetBookStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookInfoByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookInfoByID", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetBookInfoByIDRequestBody Body;
        
        public GetBookInfoByIDRequest() {
        }
        
        public GetBookInfoByIDRequest(ExportToVufind.test.GetBookInfoByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookInfoByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetBookInfoByIDRequestBody() {
        }
        
        public GetBookInfoByIDRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookInfoByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookInfoByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetBookInfoByIDResponseBody Body;
        
        public GetBookInfoByIDResponse() {
        }
        
        public GetBookInfoByIDResponse(ExportToVufind.test.GetBookInfoByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookInfoByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookInfoByIDResult;
        
        public GetBookInfoByIDResponseBody() {
        }
        
        public GetBookInfoByIDResponseBody(string GetBookInfoByIDResult) {
            this.GetBookInfoByIDResult = GetBookInfoByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookInfoByInvNumberRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookInfoByInvNumber", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetBookInfoByInvNumberRequestBody Body;
        
        public GetBookInfoByInvNumberRequest() {
        }
        
        public GetBookInfoByInvNumberRequest(ExportToVufind.test.GetBookInfoByInvNumberRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookInfoByInvNumberRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string invNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        public GetBookInfoByInvNumberRequestBody() {
        }
        
        public GetBookInfoByInvNumberRequestBody(string invNumber, string id) {
            this.invNumber = invNumber;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookInfoByInvNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookInfoByInvNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.GetBookInfoByInvNumberResponseBody Body;
        
        public GetBookInfoByInvNumberResponse() {
        }
        
        public GetBookInfoByInvNumberResponse(ExportToVufind.test.GetBookInfoByInvNumberResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookInfoByInvNumberResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBookInfoByInvNumberResult;
        
        public GetBookInfoByInvNumberResponseBody() {
        }
        
        public GetBookInfoByInvNumberResponseBody(string GetBookInfoByInvNumberResult) {
            this.GetBookInfoByInvNumberResult = GetBookInfoByInvNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePWDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePWD", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.ChangePWDRequestBody Body;
        
        public ChangePWDRequest() {
        }
        
        public ChangePWDRequest(ExportToVufind.test.ChangePWDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePWDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public ChangePWDRequestBody() {
        }
        
        public ChangePWDRequestBody(int number, string pwd) {
            this.number = number;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePWDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePWDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ExportToVufind.test.ChangePWDResponseBody Body;
        
        public ChangePWDResponse() {
        }
        
        public ChangePWDResponse(ExportToVufind.test.ChangePWDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangePWDResponseBody {
        
        public ChangePWDResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : ExportToVufind.test.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<ExportToVufind.test.ServiceSoap>, ExportToVufind.test.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.GetReaderInfoResponse ExportToVufind.test.ServiceSoap.GetReaderInfo(ExportToVufind.test.GetReaderInfoRequest request) {
            return base.Channel.GetReaderInfo(request);
        }
        
        public ExportToVufind.test.ReaderInfo GetReaderInfo(string NumberReader) {
            ExportToVufind.test.GetReaderInfoRequest inValue = new ExportToVufind.test.GetReaderInfoRequest();
            inValue.Body = new ExportToVufind.test.GetReaderInfoRequestBody();
            inValue.Body.NumberReader = NumberReader;
            ExportToVufind.test.GetReaderInfoResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).GetReaderInfo(inValue);
            return retVal.Body.GetReaderInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.AuthorizeResponse ExportToVufind.test.ServiceSoap.Authorize(ExportToVufind.test.AuthorizeRequest request) {
            return base.Channel.Authorize(request);
        }
        
        public string Authorize(string login, string password) {
            ExportToVufind.test.AuthorizeRequest inValue = new ExportToVufind.test.AuthorizeRequest();
            inValue.Body = new ExportToVufind.test.AuthorizeRequestBody();
            inValue.Body.login = login;
            inValue.Body.password = password;
            ExportToVufind.test.AuthorizeResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).Authorize(inValue);
            return retVal.Body.AuthorizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.HashPassResponse ExportToVufind.test.ServiceSoap.HashPass(ExportToVufind.test.HashPassRequest request) {
            return base.Channel.HashPass(request);
        }
        
        public string HashPass(string strPassword, string strSol) {
            ExportToVufind.test.HashPassRequest inValue = new ExportToVufind.test.HashPassRequest();
            inValue.Body = new ExportToVufind.test.HashPassRequestBody();
            inValue.Body.strPassword = strPassword;
            inValue.Body.strSol = strSol;
            ExportToVufind.test.HashPassResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).HashPass(inValue);
            return retVal.Body.HashPassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.GetLoginTypeResponse ExportToVufind.test.ServiceSoap.GetLoginType(ExportToVufind.test.GetLoginTypeRequest request) {
            return base.Channel.GetLoginType(request);
        }
        
        public string GetLoginType(string login) {
            ExportToVufind.test.GetLoginTypeRequest inValue = new ExportToVufind.test.GetLoginTypeRequest();
            inValue.Body = new ExportToVufind.test.GetLoginTypeRequestBody();
            inValue.Body.login = login;
            ExportToVufind.test.GetLoginTypeResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).GetLoginType(inValue);
            return retVal.Body.GetLoginTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.GetUserResponse ExportToVufind.test.ServiceSoap.GetUser(ExportToVufind.test.GetUserRequest request) {
            return base.Channel.GetUser(request);
        }
        
        public ExportToVufind.test.ReaderInfo GetUser(string login) {
            ExportToVufind.test.GetUserRequest inValue = new ExportToVufind.test.GetUserRequest();
            inValue.Body = new ExportToVufind.test.GetUserRequestBody();
            inValue.Body.login = login;
            ExportToVufind.test.GetUserResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).GetUser(inValue);
            return retVal.Body.GetUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.InsertIntoBasketResponse ExportToVufind.test.ServiceSoap.InsertIntoBasket(ExportToVufind.test.InsertIntoBasketRequest request) {
            return base.Channel.InsertIntoBasket(request);
        }
        
        public bool InsertIntoBasket(int PIN, string IDSession) {
            ExportToVufind.test.InsertIntoBasketRequest inValue = new ExportToVufind.test.InsertIntoBasketRequest();
            inValue.Body = new ExportToVufind.test.InsertIntoBasketRequestBody();
            inValue.Body.PIN = PIN;
            inValue.Body.IDSession = IDSession;
            ExportToVufind.test.InsertIntoBasketResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).InsertIntoBasket(inValue);
            return retVal.Body.InsertIntoBasketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.InsertArrayIntoBasketResponse ExportToVufind.test.ServiceSoap.InsertArrayIntoBasket(ExportToVufind.test.InsertArrayIntoBasketRequest request) {
            return base.Channel.InsertArrayIntoBasket(request);
        }
        
        public bool InsertArrayIntoBasket(ExportToVufind.test.ArrayOfInt PINs, string IDSession) {
            ExportToVufind.test.InsertArrayIntoBasketRequest inValue = new ExportToVufind.test.InsertArrayIntoBasketRequest();
            inValue.Body = new ExportToVufind.test.InsertArrayIntoBasketRequestBody();
            inValue.Body.PINs = PINs;
            inValue.Body.IDSession = IDSession;
            ExportToVufind.test.InsertArrayIntoBasketResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).InsertArrayIntoBasket(inValue);
            return retVal.Body.InsertArrayIntoBasketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.GetExemplarStatusResponse ExportToVufind.test.ServiceSoap.GetExemplarStatus(ExportToVufind.test.GetExemplarStatusRequest request) {
            return base.Channel.GetExemplarStatus(request);
        }
        
        public string GetExemplarStatus(string IDDATA, string BaseName) {
            ExportToVufind.test.GetExemplarStatusRequest inValue = new ExportToVufind.test.GetExemplarStatusRequest();
            inValue.Body = new ExportToVufind.test.GetExemplarStatusRequestBody();
            inValue.Body.IDDATA = IDDATA;
            inValue.Body.BaseName = BaseName;
            ExportToVufind.test.GetExemplarStatusResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).GetExemplarStatus(inValue);
            return retVal.Body.GetExemplarStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.GetBookStatusResponse ExportToVufind.test.ServiceSoap.GetBookStatus(ExportToVufind.test.GetBookStatusRequest request) {
            return base.Channel.GetBookStatus(request);
        }
        
        public string GetBookStatus(string id) {
            ExportToVufind.test.GetBookStatusRequest inValue = new ExportToVufind.test.GetBookStatusRequest();
            inValue.Body = new ExportToVufind.test.GetBookStatusRequestBody();
            inValue.Body.id = id;
            ExportToVufind.test.GetBookStatusResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).GetBookStatus(inValue);
            return retVal.Body.GetBookStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.GetBookInfoByIDResponse ExportToVufind.test.ServiceSoap.GetBookInfoByID(ExportToVufind.test.GetBookInfoByIDRequest request) {
            return base.Channel.GetBookInfoByID(request);
        }
        
        public string GetBookInfoByID(string id) {
            ExportToVufind.test.GetBookInfoByIDRequest inValue = new ExportToVufind.test.GetBookInfoByIDRequest();
            inValue.Body = new ExportToVufind.test.GetBookInfoByIDRequestBody();
            inValue.Body.id = id;
            ExportToVufind.test.GetBookInfoByIDResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).GetBookInfoByID(inValue);
            return retVal.Body.GetBookInfoByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.GetBookInfoByInvNumberResponse ExportToVufind.test.ServiceSoap.GetBookInfoByInvNumber(ExportToVufind.test.GetBookInfoByInvNumberRequest request) {
            return base.Channel.GetBookInfoByInvNumber(request);
        }
        
        public string GetBookInfoByInvNumber(string invNumber, string id) {
            ExportToVufind.test.GetBookInfoByInvNumberRequest inValue = new ExportToVufind.test.GetBookInfoByInvNumberRequest();
            inValue.Body = new ExportToVufind.test.GetBookInfoByInvNumberRequestBody();
            inValue.Body.invNumber = invNumber;
            inValue.Body.id = id;
            ExportToVufind.test.GetBookInfoByInvNumberResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).GetBookInfoByInvNumber(inValue);
            return retVal.Body.GetBookInfoByInvNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ExportToVufind.test.ChangePWDResponse ExportToVufind.test.ServiceSoap.ChangePWD(ExportToVufind.test.ChangePWDRequest request) {
            return base.Channel.ChangePWD(request);
        }
        
        public void ChangePWD(int number, string pwd) {
            ExportToVufind.test.ChangePWDRequest inValue = new ExportToVufind.test.ChangePWDRequest();
            inValue.Body = new ExportToVufind.test.ChangePWDRequestBody();
            inValue.Body.number = number;
            inValue.Body.pwd = pwd;
            ExportToVufind.test.ChangePWDResponse retVal = ((ExportToVufind.test.ServiceSoap)(this)).ChangePWD(inValue);
        }
    }
}
